// Integration test for the SPLIT nose files (dino_probe/export_nose.py --split): a MODEL-only .bin and an
// EMBEDDINGS-only .bin load independently and score via the ported RBF-SVM, and a mismatched pairing
// (one dataset's embeddings + another's model) is a valid TRANSFER run. Skips if the artifacts aren't
// present (they're generated by export_nose, not committed).
import { existsSync, readFileSync } from "node:fs";
import { describe, it, expect } from "vitest";
import { parseClassifier, rbfProbability } from "./qc/embedding/svm.js";

const MODEL = (ds) => new URL(`../../public/nose_models/nose_model_${ds}__p48.bin`, import.meta.url);
const EMB = (ds) => new URL(`../../precomputed/nose_emb_${ds}__p48.bin`, import.meta.url);

function readBin(url) {
  const b = readFileSync(url);
  return b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength); // -> ArrayBuffer
}
function header(ab) {
  const hlen = new DataView(ab).getUint32(0, true);
  return { h: JSON.parse(new TextDecoder().decode(new Uint8Array(ab, 4, hlen))), f32Start: 4 + hlen };
}
function loadModel(ds) {
  const ab = readBin(MODEL(ds));
  const { h, f32Start } = header(ab);
  const nFloats = h.dim + h.dim + h.n_sv + h.n_sv * h.dim; // mean|scale|dual|sv
  return { h, clf: parseClassifier(h, ab.slice(f32Start, f32Start + nFloats * 4)) };
}
function loadEmb(ds) {
  const ab = readBin(EMB(ds));
  const { h, f32Start } = header(ab);
  const flat = new Float32Array(ab, f32Start, h.n * h.dim);
  const embs = new Array(h.n);
  for (let i = 0; i < h.n; i++) embs[i] = flat.subarray(i * h.dim, i * h.dim + h.dim);
  return { h, embs };
}

const present = ["center_no_gily", "gily_only"].every((ds) => existsSync(MODEL(ds)) && existsSync(EMB(ds)));
const d = present ? describe : describe.skip;

d("split nose files (model + embeddings load separately)", () => {
  it("model and embeddings headers are self-describing and dim-compatible", () => {
    const { h: m } = loadModel("center_no_gily");
    const { h: e } = loadEmb("center_no_gily");
    expect(m.kind).toBe("nose-model");
    expect(e.kind).toBe("nose-emb");
    expect(m.dim).toBe(e.dim);                       // scorable pairing
    expect(m.n_sv).toBeGreaterThan(0);
    expect(m.platt_a).toBeTypeOf("number");          // calibrated
    expect(e.video.length).toBe(e.n);                // index aligns to embeddings
  });

  it("self pairing (own model) scores every patch to a calibrated probability", () => {
    const { clf } = loadModel("center_no_gily");
    const { embs } = loadEmb("center_no_gily");
    const p = rbfProbability(embs, clf);
    expect(p.length).toBe(embs.length);
    expect(Math.min(...p)).toBeGreaterThanOrEqual(0);
    expect(Math.max(...p)).toBeLessThanOrEqual(1);
    expect(new Set(p).size).toBeGreaterThan(10);      // not a constant
  });

  it("TRANSFER: this dataset's embeddings score under another dataset's model, and differ from self", () => {
    const { embs } = loadEmb("center_no_gily");
    const self = rbfProbability(embs, loadModel("center_no_gily").clf);
    const xfer = rbfProbability(embs, loadModel("gily_only").clf);   // gily model on center noses
    expect(xfer.length).toBe(embs.length);
    expect(Math.min(...xfer)).toBeGreaterThanOrEqual(0);
    expect(Math.max(...xfer)).toBeLessThanOrEqual(1);
    // the two models rank patches differently — a real transfer, not the same scores
    let diff = 0;
    for (let i = 0; i < self.length; i++) diff += Math.abs(self[i] - xfer[i]);
    expect(diff / self.length).toBeGreaterThan(0.01);
  });
});
